### ISSUE TITLE
Put collision parameter name

### ISSUE THREAD

**Issue by NelaMm** [robofit/arcor2_kinali#31]
Method add collision - uncompatible collision parameter name: boxId/sphereId/meshId instead of Id

**Comment by ZdenekM** [comment]
@NelaMm Thank you for your report. But could you describe more where the problem is? There is "id" in the parameters of the REST API call, see https://github.com/robofit/arcor2_kinali/blob/master/arcor2_kinali/services/robot.py#L47.

**Comment by NelaMm** [comment]
It should have be boxId/sphereId/meshId instead of Id. Sorry for my wrong expression of the problem.

**Comment by ZdenekM** [comment]
Current version of arcor2 and arcor2_kinali is intended to be used with the robot service version 0.2.1 (see https://github.com/robofit/arcor2_kinali/blob/master/docker/docker-compose.yml#L49) which uses "id". Parameter "id" changed to "boxId/sphereId/meshId" in the robot service version 0.3.0 which was not available when the last version of arcor2 was released.

**Comment by ZdenekM** [comment]
OK, now I realized that robot service 0.3.0 was released 3 weeks ago. Sorry, we somehow missed this release and tested arcor2 with the old one. New version of arcor2 will be compatible and tested with the current version of robot service (0.3.1).

**Comment by martincervinka** [comment]
The last official version of the robot service is 0.3.0. Version 0.3.1-rc.1 was accidentally published. I'm sorry about that. We do not want to test robot service in version 0.2.1 anymore. This incompatibility is critical for our test scenario and we are not going to test ARCOR2 until it is fixed. When can we expect this fix, please?

**Comment by ZdenekM** [comment]
I just added changes making this repo compatible with robot service 0.3.0. @Kapim could you please make a new release?

**Comment by Kapim** [comment]
Fixed in #32, released version 0.3.1 of images arcor2_arserver_kinali and arcor2_execution_kinali. See updated docker_compose (each service has own env variable now).
