### ISSUE TITLE
Method scan in Barcode service does not work

### ISSUE THREAD

**Issue by hanapelikanova** [robofit/arcor2_kinali#49]
When calling scan method in attached testing script, script crashes and the process finishes with returncode 0. Method active_scanners works, so it is not problem of communication between services.

![BarcodeServiceBug](https://user-images.githubusercontent.com/61684291/82808044-63c84980-9e89-11ea-9d6e-be7d10521f48.PNG)

[TestScript_BugReport.zip](https://github.com/robofit/arcor2_kinali/files/4676893/TestScript_BugReport.zip)

**Comment by ZdenekM** [comment]
The problem was in request header. I just fixed this in https://github.com/robofit/arcor2/commit/720e75046fcc268f8a05d347adba46c099031eb1 and it will appear in the following (regular) release. If this is somehow critical, please let me know and we can make bugfix release.

**Comment by hanapelikanova** [comment]
Thank you for the quick response. This is not critical for us, next regular release is alright.
