### ISSUE TITLE
New version of ARCOR2 Execution Service

### ISSUE THREAD

**Issue by hanapelikanova** [robofit/arcor2_kinali#60]
New version of KINALI Execution Service was released today: https://gitlab.com/kinalisoft/test-it-off/execution/-/blob/master/swagger.json. Please implement new version of ARCOR2 Execution Service at your soonest convenience as it is necessary for Web UI testing.

**Comment by ZdenekM** [comment]
The service is prepared. We will release it next week as colleague (@Kapim) who is doing releases is on vacation at the moment.

**Comment by ZdenekM** [comment]
OpenAPI documents are already awailable:
https://robofit.github.io/arcor2/0.7.0/swagger/build_service/ (no change)
https://robofit.github.io/arcor2/0.7.0/swagger/execution_service_proxy/

**Comment by martincervinka** [comment]
Thanks, Execution API looks the same as defined in [Execution Web API Reference](https://gitlab.com/kinalisoft/test-it-off/execution/-/blob/master/swagger.json). It would be nice if you could divide your repository and mainly separate the release cycle of your microservices. Currently, we have the second version of Execution API and to have a version of ARCOR2 Execution service 0.7.x is a bit confusing.

**Comment by ZdenekM** [comment]
We are definitely going to divide the repository (https://github.com/robofit/arcor2/issues/156).
