### ISSUE TITLE
Implement add collision box/sphere/mesh in robot service

### ISSUE THREAD

**Issue by NelaMm** [robofit/arcor2_kinali#61]
When I want to use only robot service in script (without scene.json/project.json), I don't know how to add box/sphere/mesh with specific parameters.

**Comment by martincervinka** [comment]
Can you fix this ASAP, please? We can not use just Python scripting without hacks. Working Python scripting and Execution service has the highest priority now.  It's a basic scenario for August.

**Comment by ZdenekM** [comment]
Fixed in https://github.com/robofit/arcor2_kinali/pull/64/commits/9efd1d6ddf932fe0a2f8db49ebe19bafa25185e8.

**Comment by martincervinka** [comment]
Thank you. How can we find out when a new version with this fix will be approximately released? Can you use Milestones?

**Comment by Kapim** [comment]
It will be today.
