### ISSUE TITLE
Not able to set up LogLevel for SearchService

### ISSUE THREAD

**Issue by ghost** [robofit/arcor2_kinali#70]
When running enclosed LogLevelScript.py script in docker container with arcor2/arcor2_base_kinali image, I am not able to set up LogLevel. Line `parameters = SearchEngineParameters(search_log_level = LogLevel.DEBUG)` raises RestException: 'The JSON value could not be converted to Kinalisoft.Search.SearchLogLevel. Path: $.SearchLogLevel | LineNumber: 0 | BytePositionInLine: 26.'

[LogLevelScript.zip](https://github.com/robofit/arcor2_kinali/files/4932251/LogLevelScript.zip)

**Comment by ZdenekM** [comment]
Looks like we missed the ```SearchLogLevel``` model... The code should be like this:

```python
parameters = SearchEngineParameters(search_log_level=SearchLogLevel(LogLevel.DEBUG))
```

The missing model will be added in the upcoming release, thanks for reporting.

**Comment by ZdenekM** [comment]
Fixed by https://github.com/robofit/arcor2_kinali/commit/6aedcbe7c9d29b52f7c30b8e1cc5cb28f4c52162.
