### ISSUE TITLE
Client request time out

### ISSUE THREAD

**Issue by NelaMm** [robofit/arcor2_kinali#82]
Can you please increase limit for request timed out. For example I call move with very slow speed and request timed out before robot ended execution of move.

**Comment by ZdenekM** [comment]
Ok, I will increase the timeout for KinaliRobot to 5 minutes. That should be hopefully enough. We will make a new release with this change soon.

**Comment by ZdenekM** [comment]
@NelaMm Should we make a new release? Or could we add this change to the next regular release?

**Comment by martincervinka** [comment]
Yes, create a release, please. Include [Scene service implementation issue](https://github.com/robofit/arcor2_kinali/issues/83) too please.
